"""Gemini client helpers for generating PR reviews."""

from __future__ import annotations

DEFAULT_GEMINI_MODEL = "gemini-2.5-flash-lite"


class LLMClientError(RuntimeError):
    """Raised when the LLM client cannot generate a usable response."""


def generate_review(
    prompt: str,
    *,
    model: str = DEFAULT_GEMINI_MODEL,
    api_key: str | None = None,
) -> str:
    """Return a PR review generated by Gemini for the given prompt."""
    if not prompt.strip():
        raise ValueError("Prompt must not be empty")

    try:
        from dotenv import load_dotenv
        from google import genai
    except ModuleNotFoundError as exc:  # pragma: no cover - depends on local env
        raise LLMClientError(f"Missing dependency: {exc.name}") from exc

    load_dotenv()
    client = genai.Client(api_key=api_key) if api_key else genai.Client()

    try:
        response = client.models.generate_content(model=model, contents=prompt)
    except Exception as exc:  # pragma: no cover - depends on remote API behavior
        raise LLMClientError(f"Gemini request failed: {exc}") from exc

    response_text = getattr(response, "text", None)
    if not response_text or not response_text.strip():
        raise LLMClientError("Gemini returned an empty response")

    return response_text.strip()
